### ISSUE TITLE
Metadata: pr does not follow CF-convention

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/dummydata#3]
According to the CF-convention, standard_name should be precipitation_flux instead of precipitation for variable 'pr'.

**Comment by bouweandela** [comment]
Maybe it would be better to get the information in the Metadata class from an external source, e.g. autogenerate from the cf-convention xml document, or import from another Python package, instead of hardcoding.

**Comment by bjoernbroetz** [comment]
Right! This cf-convention is also subject to change (new variables can enter). This should be external. There will be a new issue for that.
